version: '3'
networks:
  myNetwork:
    driver: bridge
services:
  client:
    container_name: 'gino-memory-client'
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    ports: 
      - 5173:5173
    tty: true
    depends_on:
      - db
      - backend
    networks:
      - myNetwork
    volumes:
      - ./client:/app
    
  backend:
    container_name: 'gino-memory-backend'
    build: ./server
    restart: always
    ports: 
      - 3000:3000
    depends_on:
      - db
    networks:
      - myNetwork
    environment:
      - environment=development
      - mongoDBUrI=mongodb://db:27017
      - jwtSecretKey=jwtSecretKey
    volumes:
      - ./server:/usr/src/app
  db:
    image: 'mongo'
    container_name: 'gino-memory-db'
    ports:
      - 27017:27017
    networks:
      - myNetwork
    volumes:
      - ./tmp/data/db:/data/db
  nginx: 
    image: 'nginx:stable-alpine'
    ports:
      - 7070:80
    depends_on:
      - db
      - backend
      - client
    volumes:
      - ./client/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - myNetwork
    tty: true
