name: deploy to gcp 
on: 
  push:
    branches: [ main ]
jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME: ginoking-memory-v1
      PROJECT_ID: memory-410003
      REPOSITORY: asia-east1-docker.pkg.dev
    strategy:
      matrix: 
        include: 
          - dockerfile: ./client/Dockerfile
            image: asia-east1-docker.pkg.dev/memory-410003/memory/ginoking-memory-v1-client
          - dockerfile: ./server/Dockerfile
            image: asia-east1-docker.pkg.dev/memory-410003/memory/ginoking-memory-v1-server
    permissions:
      id-token: write
      contents: read
    steps: 
      - name: check out code
        uses: actions/checkout@v4
      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: semver
          increment: patch
      - name: configure GCP credentials
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: memory-410003
          token_format: access_token 
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
      - name: login to Artifact Registry
        uses: docker/login-action@v1
        with: 
          registry: asia-east1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}
      - name: build and push image
        uses: docker/build-push-action@v5
        id: build-image
        with: 
          file: ${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

