name: deploy to gcp 
on: 
  push:
    branches: [ main ]
jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME: ginoking-memory-v1
      PROJECT_ID: memory-410003
      REPOSITORY: asia-east1-docker.pkg.dev
    permissions:
      id-token: write
      contents: read
    steps: 
      - name: check out code
        uses: actions/checkout@v4
      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: semver
          increment: patch
      - name: configure GCP credentials
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: memory-410003
          token_format: access_token 
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
      - name: login to Artifact Registry
        uses: docker/login-action@v1
        with: 
          registry: asia-east1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: build image
        id: build-image
        run: docker build -t $IMAGE_NAME:latest .
      - name: push image to gcp gar
        env:
          GIT_TAG: ${{ steps.version.outputs.version }}l
        run: |-
          docker tag $IMAGE_NAME:latest $REPOSITORY/$PROJECT_ID/memory/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest $REPOSITORY/$PROJECT_ID/memory/$IMAGE_NAME:$GIT_TAG
          docker push $REPOSITORY/$PROJECT_ID/memory/$IMAGE_NAME:latest
          docker push $REPOSITORY/$PROJECT_ID/memory/$IMAGE_NAME:$GIT_TAG

