name: deploy to aws ecr
on: 
  push:
    branches: [ main ]
jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    steps: 
      - name: check out code
        uses: actions/checkout@v2
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: AKIATGEEGLA6WXFPCKW4
          aws-secret-access-key: 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
          aws-region: ap-east-1
          
      - name: login aws ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: build and push image to aws ecr
        id: build-image
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          IMAGE_TAG: latest
        run: 
          cd server
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

